In [1]:
import numpy as np


In [4]:
list01 = [  np.array([1,2,3,4,5]),
        np.array([6,7,8,9,10]),
         np.array([11,12,13,14,15]) ]
result = []

#to find mean of every array  
for i in  range (len(list01)):
    result.append(np.mean(list01[i]))
print(result)


[3.0, 8.0, 13.0]


In [5]:

# to add the new row in  an array
v = np.array([16,17,18,19,20])
n  = np.vstack((list01,v))
print(n)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [7]:
n

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [15]:
# to sorting the value in array
g = np.argsort(n, axis = None)
g
g = np.argsort(n, axis = 0)
g
g = np.argsort(n, axis = 1)
g

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int64)

In [11]:
# to find the max and mini value in aray
v = np.max(n),np.min(n)
v

(20, 1)