In [1]:
import time
import numpy as np

In [2]:
def genrate_time(in_sec):
   total_sec = in_sec*60
   for i in range(total_sec+1):
      sec =  i%60
      min = i//60
      yield f"{min:02} :{sec:02}"
for j in genrate_time(3):
    time.sleep(0.1)
    print(j)

00 :00
00 :01
00 :02
00 :03
00 :04
00 :05
00 :06
00 :07
00 :08
00 :09
00 :10
00 :11
00 :12
00 :13
00 :14
00 :15
00 :16
00 :17
00 :18
00 :19
00 :20
00 :21
00 :22
00 :23
00 :24
00 :25
00 :26
00 :27
00 :28
00 :29
00 :30
00 :31
00 :32
00 :33
00 :34
00 :35
00 :36
00 :37
00 :38
00 :39
00 :40
00 :41
00 :42
00 :43
00 :44
00 :45
00 :46
00 :47
00 :48
00 :49
00 :50
00 :51
00 :52
00 :53
00 :54
00 :55
00 :56
00 :57
00 :58
00 :59
01 :00
01 :01
01 :02
01 :03
01 :04
01 :05
01 :06
01 :07
01 :08
01 :09
01 :10
01 :11
01 :12
01 :13
01 :14
01 :15
01 :16
01 :17
01 :18
01 :19
01 :20
01 :21
01 :22
01 :23
01 :24
01 :25
01 :26
01 :27
01 :28
01 :29
01 :30
01 :31
01 :32
01 :33
01 :34
01 :35
01 :36
01 :37
01 :38
01 :39
01 :40
01 :41
01 :42
01 :43
01 :44
01 :45
01 :46
01 :47
01 :48
01 :49
01 :50
01 :51
01 :52
01 :53
01 :54
01 :55
01 :56
01 :57
01 :58
01 :59
02 :00
02 :01
02 :02
02 :03
02 :04
02 :05
02 :06
02 :07
02 :08
02 :09
02 :10
02 :11
02 :12
02 :13
02 :14
02 :15
02 :16
02 :17
02 :18
02 :19
02 :20
02 :21
02 :22

In [ ]:
a  =np.array([1,2])
a.dtype

In [ ]:
a = np.zeros([2,3])
a

In [ ]:
a = np.array([[1,2],[3,4]])
a

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a.shape

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a.ndim

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a.size

In [ ]:
a = np.empty([2,5],dtype=int)
a

In [ ]:
a = np.eye(5)
a

In [ ]:
a = np.arange(1,5,-1,dtype=None)
a

In [ ]:
a = 2

v = [(n*a) for n in range(8)]
m  = [(n*a) for n in np.arange(8)]
v
m

In [ ]:
a = np.linspace(0,3,4)
a

In [ ]:
a = np.logspace(0,3,base=2,endpoint=False)
a

In [ ]:
a = np.logspace(0,3,endpoint = True)
a

In [ ]:
a = np.geomspace(1,4,num=3)
a

In [6]:
a = np.geomspace(1,4)
a

array([1.        , 1.02869573, 1.05821491, 1.08858117, 1.1198188 ,
       1.15195282, 1.18500895, 1.21901365, 1.25399415, 1.28997843,
       1.3269953 , 1.36507441, 1.40424622, 1.44454209, 1.48599429,
       1.52863599, 1.57250132, 1.61762539, 1.66404434, 1.71179531,
       1.76091654, 1.81144733, 1.86342814, 1.91690058, 1.97190744,
       2.02849277, 2.08670186, 2.1465813 , 2.20817903, 2.27154434,
       2.33672798, 2.4037821 , 2.47276039, 2.54371806, 2.61671192,
       2.69180039, 2.76904357, 2.84850331, 2.9302432 , 3.01432868,
       3.10082705, 3.18980756, 3.28134142, 3.37550192, 3.47236443,
       3.57200647, 3.67450782, 3.77995051, 3.88841897, 4.        ])

In [13]:
a = np.arange(1,50,4)
a

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49])

In [8]:
a  = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [14]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [15]:
a = np.array([1,2,3,4])
a1 = a.reshape(2,2)
a1

array([[1, 2],
       [3, 4]])

In [16]:
a
b = np.array([5,6])
c  = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [17]:
a1 = np.split(c,3)
a1

[array([1, 2]), array([3, 4]), array([5, 6])]

In [18]:
a3  = np.split(c,[3,3])

a3

[array([1, 2, 3]), array([], dtype=int64), array([4, 5, 6])]

In [19]:
a  =np.array([[1,2],[3,4],[5,6],[7,8]])

a1 = np.split(a,2,axis=0)
a1


[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [20]:
a  =np.array([[1,2],[3,4],[5,6],[7,8]])

a1 = np.split(a,2,axis=1)
a1


[array([[1],
        [3],
        [5],
        [7]]),
 array([[2],
        [4],
        [6],
        [8]])]

In [21]:
#insert a value
a = np.array([[1,2],[3,4]])
a1 = np.insert(a,2,[6,7],axis=1)
a1

array([[1, 2, 6],
       [3, 4, 7]])

In [22]:
a  =np.array([[1,2,3],[4,5,6]])
a1 = np.split(a,2)
a1

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [23]:
a = np.ones([4,3])
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
a =  np.ones([2,2])
a

array([[1., 1.],
       [1., 1.]])

In [25]:
a = np.array([[2,3,5],[22,3,4]])
a
a1 = np.sort(a)
a1



array([[ 2,  3,  5],
       [ 3,  4, 22]])

In [26]:
b = [n for n in np.linspace(0,4)]
b

[np.float64(0.0),
 np.float64(0.08163265306122448),
 np.float64(0.16326530612244897),
 np.float64(0.24489795918367346),
 np.float64(0.32653061224489793),
 np.float64(0.4081632653061224),
 np.float64(0.4897959183673469),
 np.float64(0.5714285714285714),
 np.float64(0.6530612244897959),
 np.float64(0.7346938775510203),
 np.float64(0.8163265306122448),
 np.float64(0.8979591836734693),
 np.float64(0.9795918367346939),
 np.float64(1.0612244897959182),
 np.float64(1.1428571428571428),
 np.float64(1.2244897959183672),
 np.float64(1.3061224489795917),
 np.float64(1.3877551020408163),
 np.float64(1.4693877551020407),
 np.float64(1.5510204081632653),
 np.float64(1.6326530612244896),
 np.float64(1.7142857142857142),
 np.float64(1.7959183673469385),
 np.float64(1.8775510204081631),
 np.float64(1.9591836734693877),
 np.float64(2.0408163265306123),
 np.float64(2.1224489795918364),
 np.float64(2.204081632653061),
 np.float64(2.2857142857142856),
 np.float64(2.36734693877551),
 np.float64(2.4489795918

In [27]:
a = np.linspace(0,50,2)
a

array([ 0., 50.])

In [28]:
n = np.array([[1,2],[3,4]])
m = np.array([[6,7],[6,7]])
j = np.concatenate((n,m))
j

array([[1, 2],
       [3, 4],
       [6, 7],
       [6, 7]])

In [29]:
k = np.split(n,2)
k
b =  np.add(m,[4,5])
b
k = np.ceil(m)
k
n = np.array([[2,-2,4],[6,-4,-1]])
l = np.abs(n)
m
h = np.array([[2,4.6],[5,6.3]])
o = np.floor(h)
o

array([[2., 4.],
       [5., 6.]])

In [30]:
b  =5
m =[n % b == 0 for n in np.array([[1,2,3,4,5],[6,7,8,9,10]])]
m

[array([False, False, False, False,  True]),
 array([False, False, False, False,  True])]

In [31]:
m = np.array([[1,2,3],[4,5,6]])
n = np.array([[7,8,9],[10,11,12]])
p = np.hstack((m,n))
p

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [32]:
# p = np.vstack((m,n))
# p

In [33]:
m.swapaxes(1,1)


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a  = np.random.rand(2,3)
a

In [ ]:
a = np.eye(3)
a

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a.T
# a.flatten()